### ISSUE TITLE
can you help to understand why my id sandy4321 is so many times in links in your data?

### ISSUE THREAD

**Issue by Sandy4321** [fronchetti/SANER-2018#3]
can you help to understand why my id sandy4321 is so many times in links in this file?
https://github.com/fronchetti/SANER-2018/blob/cc7d788875f4472d849f00a43e3a307b3f20d4eb/Dataset/rospca/forks.json

like
"issues_url": "https://api.github.com/repos/Sandy4321/rospca/issues{/number}", 
        "deployments_url": "https://api.github.com/repos/Sandy4321/rospca/deployments", 
        "stargazers_count": 0, 
        "forks_url": "https://api.github.com/repos/Sandy4321/rospca/forks", 
        "mirror_url": null, 
        "subscription_url": "https://api.github.com/repos/Sandy4321/rospca/subscription", 
        "notifications_url": "https://api.github.com/repos/Sandy4321/rospca/notifications{?since,all,participating}", 
        "collaborators_url": "https://api.github.com/repos/Sandy4321/rospca/collaborators{/collaborator}", 
        "updated_at": "2017-01-27T21:15:44Z", 
        "private": false, 
        "pulls_url": "https://api.github.com/repos/Sandy4321/rospca/pulls{/number}", 
        "issue_comment_url": "https://api.github.com/repos/Sandy4321/rospca/issues/comments{/number}", 
        "labels_url": "https://api.github.com/repos/Sandy4321/rospca/labels{/name}", 
        "has_wiki": true, 
        "full_name": "Sandy4321/rospca", 

![image](https://user-images.githubusercontent.com/11426119/74482265-30395480-4e82-11ea-94f8-e210783d3405.png)

**Comment by fronchetti** [comment]
In our paper, one of the repositories that we analyzed is https://github.com/TReynkens/rospca/, an R package. You have a fork of this repository in your GitHub account (https://github.com/Sandy4321/rospca). For this reason, your username appears in the forks.json file of this project.

If you want, I can remove your name from this file.

Thanks,
Felipe

**Comment by fronchetti** [comment]
By the way, all the information that we collected in our study was extracted using GitHub API for public repositories, which means that forks.json was made publicly available for everyone by GitHub (You accepted their privacy agreements when you registered your account).

Example:
https://api.github.com/repos/Sandy4321/rospca

**Comment by Sandy4321** [comment]
All ok thanks
Please keep it
In like to see that my efforts now used as example how scientists do research
Thanks
